---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - namespace: ${releaseNamespace}
      name: kube-prometheus-stack
  chart:
    spec:
      chart: prometheus-adapter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community.github.io-helm-charts
        namespace: kommander-flux
      version: 2.11.1
  interval: 15s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  releaseName: prometheus-adapter
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-adapter-2.11.1-d2iq-defaults
  targetNamespace: ${releaseNamespace}
