apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - namespace: ${workspaceNamespace}
      name: traefik
  chart:
    spec:
      chart: traefik-forward-auth
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-charts-staging
        namespace: kommander-flux
      version: 0.3.10
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: traefik-forward-auth
  valuesFrom:
    - kind: ConfigMap
      name: traefik-forward-auth-0.3.11-d2iq-defaults
  targetNamespace: ${releaseNamespace}
