apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${appName}-${releaseName}-source
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: oci://ghcr.io/mesosphere/charts/traefik-forward-auth
  ref:
    tag: 0.3.10
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-forward-auth-mgmt
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - namespace: ${releaseNamespace}
      name: traefik
    - namespace: ${releaseNamespace}
      name: dex
    - namespace: ${releaseNamespace}
      name: kommander
  chartRef:
    kind: OCIRepository
    name: ${appName}-${releaseName}-source
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: traefik-forward-auth-mgmt
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-config-defaults
    - kind: ConfigMap
      name: traefik-forward-auth-mgmt-overrides
      optional: true
  targetNamespace: ${releaseNamespace}
