apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${appName}-${releaseName}-source
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://ghcr.io/mesosphere/charts/prometheus-adapter"
  ref:
    tag: 5.1.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - namespace: ${releaseNamespace}
      name: kube-prometheus-stack
  chartRef:
    kind: OCIRepository
    name: ${appName}-${releaseName}-source
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: prometheus-adapter
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-config-defaults
  targetNamespace: ${releaseNamespace}
