apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubefed-federatedtypeconfigs
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
  path: ./services/kubefed/0.10.4/federatedtypeconfigs
  dependsOn:
    - name: kube-federation-system-namespace
    - name: kubefed-release
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  timeout: 1m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: substitution-vars
