apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kommander-flux
resources:
  - bootstrap-flux.yaml
  - ./2.6.2
patches:
  - patch: |-
      $patch: delete
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: nkp-flux-2-16-1
        namespace: ${releaseNamespace}
  - patch: |-
      $patch: delete
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: kommander-flux
        namespace: ${releaseNamespace}
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: kommander-flux-2.6.2-config-defaults
        namespace: ${releaseNamespace}
