---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - namespace: ${releaseNamespace}
      name: traefik
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-charts-staging
        namespace: kommander-flux
      version: 33.0.1
  interval: 15s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  releaseName: kube-prometheus-stack
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-33.0.1-d2iq-defaults
  targetNamespace: ${releaseNamespace}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-app-dashboard-info
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "prometheus"
data:
  name: "Prometheus"
  dashboardLink: "/dkp/prometheus"
  docsLink: "https://prometheus.io/docs/"
  # Prometheus app version can be found at prometheus.prometheusSpec.image.tag:
  # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-33.0.0/charts/kube-prometheus-stack/values.yaml#L2140
  version: "2.33.4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-app-dashboard-info
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "alertmanager"
data:
  name: "Prometheus Alert Manager"
  dashboardLink: "/dkp/alertmanager"
  docsLink: "https://prometheus.io/docs/alerting/alertmanager/"
  # Alertmanager app version can be found at alertmanager.alertmanagerSpec.image,tag:
  # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-33.0.0/charts/kube-prometheus-stack/values.yaml#L417
  version: "0.23.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-app-dashboard-info
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "grafana"
data:
  name: "Grafana"
  dashboardLink: "/dkp/grafana"
  docsLink: "https://grafana.com/docs/"
  # Since Grafana is a subchart of kube-prometheus-stack, get the version of the Grafana chart running at:
  # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-33.0.0/charts/kube-prometheus-stack/Chart.yaml#L52
  # Then, find the Grafana app version in the Grafana chart:
  # https://github.com/grafana/helm-charts/blob/grafana-6.21.2/charts/grafana/values.yaml#L76
  version: "8.3.6"
