apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubefed-federatedtypeconfigs
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  wait: true
  interval: 1m0s
  path: ./services/kubefed/0.9.1/federatedtypeconfigs
  dependsOn:
    - name: kube-federation-system-namespace
    - name: kubefed-release
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  timeout: 60s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: substitution-vars
