apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-${appVersion}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://ghcr.io/mesosphere/charts/knative"
  ref:
    tag: v1.19.5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-deploy
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - name: knative-operator
      namespace: ${releaseNamespace}
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}-chart
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: knative-deploy
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
    - kind: ConfigMap
      name: knative-config-overrides
      optional: true
    - kind: ConfigMap
      name: knative-overrides
      optional: true
