apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-post-install
  namespace: ${releaseNamespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-post-install
  namespace: ${releaseNamespace}
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["velero.io"]
    resources: ["backupstoragelocations"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-post-install
  namespace: ${releaseNamespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: velero-post-install
subjects:
  - kind: ServiceAccount
    name: velero-post-install
    namespace: ${releaseNamespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-backup-storage-location-updater
  namespace: ${releaseNamespace}
  labels:
    app: velero
    name: velero-backup-storage-location-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero
      name: velero-backup-storage-location-updater
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: velero
        name: velero-backup-storage-location-updater
    spec:
      serviceAccountName: velero-post-install
      containers:
        - name: velero-update-s3url
          image: mesosphere/kubeaddons-addon-initializer:v0.7.2
          args:
            - velero
          env:
            - name: "CEPH_NAMESPACE"
              value: ${releaseNamespace}
            - name: "CEPH_OBJECT_STORE_PORT"
              value: "8085"
            - name: "VELERO_NAMESPACE"
              value: ${releaseNamespace}
            - name: "VELERO_CEPH_OBJECT_STORE_REGION"
              value: "dkp-object-store"
            - name: "VELERO_BUCKET"
              value: "dkp-velero"
            - name: "VELERO_BACKUP_STORAGE_LOCATION"
              value: "default"
            - name: "TRAEFIK_INGRESS_SERVICE_NAME"
              value: kommander-traefik
            - name: "TRAEFIK_INGRESS_NAMESPACE"
              value: ${releaseNamespace}
