---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-${appVersion}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://ghcr.io/mesosphere/charts/thanos-traefik"
  ref:
    tag: 0.0.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karma-traefik
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}-chart
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: karma-traefik
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
