apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-loki-v3-pre-install.yaml
  - grafana-loki-v3-helmrelease.yaml
  - grafana-dashboards
  - grafana-dashboards-logging
