---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karma-traefik-0.0.2-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    enabled: true
    route:
      # TODO(mh): What domain names should we use?
      sni: server.karma.localhost.localdomain
      services:
        - name: kube-prometheus-stack-alertmanager
          port: 9093
      tls:
        secretName: kommander-karma-server-tls
    tlsoptions:
      secretName: kommander-karma-server-tls
