apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-helmrelease
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
  path: ./services/kube-prometheus-stack/65.5.0/helmrelease
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  timeout: 1m
  # passing releaseNamespace to 2nd level configuration files for ability to configure namespace correctly in attached clusters
  # Using `substituteFrom` with `substitution-vars` creates 2nd level resources in `kommander` namespace instead of workspace ns
  postBuild:
    substitute:
      releaseNamespace: ${releaseNamespace}
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kps-kube-prometheus-stack-operator
      namespace: ${releaseNamespace}
