apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./templates
  - ./helmrelease
  - ./mirror
patches:
  - path: patch-crd-controller-cluster-role.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: crd-controller
  - path: patch-proxy-env-vars.yaml
    target:
      kind: Deployment
  - path: patch-source-ctrl-network-policy.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: allow-source
      namespace: kommander-flux
