apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${appName}-${releaseName}-crds
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://ghcr.io/traefik/helm/traefik-crds"
  ref:
    tag: 1.11.1
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: ${releaseNamespace}
spec:
  interval: 15s
  chartRef:
    kind: OCIRepository
    name: ${appName}-${releaseName}-crds
    namespace: ${releaseNamespace}
  releaseName: traefik-crds
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-crds-config-defaults
    - kind: ConfigMap
      name: traefik-crd-overrides
      optional: true
