apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_ocirepositories.source.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
- apps_v1_deployment_helm-controller.yaml
- apps_v1_deployment_kustomize-controller.yaml
- apps_v1_deployment_notification-controller.yaml
- apps_v1_deployment_source-controller.yaml
- networking.k8s.io_v1_networkpolicy_allow-egress.yaml
- networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
- networking.k8s.io_v1_networkpolicy_allow-source.yaml
- networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
- rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
- rbac.authorization.k8s.io_v1_clusterrole_flux-edit-kommander-flux.yaml
- rbac.authorization.k8s.io_v1_clusterrole_flux-view-kommander-flux.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
- v1_namespace_kommander-flux.yaml
- v1_resourcequota_critical-pods-kommander-flux.yaml
- v1_service_notification-controller.yaml
- v1_service_source-controller.yaml
- v1_service_webhook-receiver.yaml
- v1_serviceaccount_helm-controller.yaml
- v1_serviceaccount_kustomize-controller.yaml
- v1_serviceaccount_notification-controller.yaml
- v1_serviceaccount_source-controller.yaml
