apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crd-helmrelease
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
  path: ./applications/traefik/39.0.1/crds
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  timeout: 1m
  postBuild:
    substitute:
      appVersion: ${appVersion}
      releaseName: ${releaseName}
      releaseNamespace: ${releaseNamespace}
    substituteFrom:
      - kind: ConfigMap
        name: substitution-vars
