apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: etcd-metrics-proxy
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
<<<<<<<< HEAD:services/kube-prometheus-stack/48.3.2/etcd-metrics-proxy.yaml
  path: ./services/kube-prometheus-stack/48.3.2/etcd-metrics-proxy
========
  path: ./services/kube-prometheus-stack/56.8.0/etcd-metrics-proxy
>>>>>>>> c39be67d (feat(kps): Bump to 56.8.0):services/kube-prometheus-stack/56.8.0/etcd-metrics-proxy.yaml
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  timeout: 1m
  # passing releaseNamespace to 2nd level configuration files for ability to configure namespace correctly in attached clusters
  # Using `substituteFrom` with `substitution-vars` creates 2nd level resources in `kommander` namespace instead of workspace ns
  postBuild:
    substitute:
      releaseNamespace: ${releaseNamespace}
      certificateIssuerKind: ${certificateIssuerKind}
      certificateIssuerName: ${certificateIssuerName}
