apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-${appVersion}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  url: "oci://ghcr.io/mesosphere/charts/kube-prometheus-stack"
  ref:
    tag: 81.3.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}-chart
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    timeout: 5m0s
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    timeout: 5m0s
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: kube-prometheus-stack
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
    - kind: ConfigMap
      name: kube-prometheus-stack-mgmt-overrides
      optional: true
  targetNamespace: ${releaseNamespace}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-app-dashboard-info
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "prometheus"
data:
  name: "Prometheus"
  dashboardLink: "/dkp/prometheus"
  docsLink: "https://prometheus.io/docs/"
  # Prometheus app version can be found at prometheus.prometheusSpec.image.tag
  version: "3.3.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-app-dashboard-info
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "alertmanager"
data:
  name: "Prometheus Alert Manager"
  dashboardLink: "/dkp/alertmanager"
  docsLink: "https://prometheus.io/docs/alerting/alertmanager/"
  # Alertmanager app version can be found at alertmanager.alertmanagerSpec.image,tag
  version: "0.28.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-app-dashboard-info
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "grafana"
data:
  name: "Grafana"
  dashboardLink: "/dkp/grafana"
  docsLink: "https://grafana.com/docs/"
  # Since Grafana is a subchart of kube-prometheus-stack, get the version of the Grafana chart dependency at:
  # https://github.com/mesosphere/charts/tree/master/staging/kube-prometheus-stack/charts
  # Then, check https://artifacthub.io/packages/helm/grafana/grafana/ for app version
  version: "12.3.3"
